### ISSUE TITLE
Add cancel button to autologin spinner

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/auth0-custom-lock#102]
In order to enable users to have agency in what identity they use to login to an RP, let's add a "cancel" button to the autologin experience at the point in time that the user sees the spinner.

Clicking it could 
* set autologin to disabled in localStorage as mentioned in #101 and take the user to the main NLX page where they could pick a new IdP
* take the user to a UI page (or possibly the settings page) where they could disable autologin (see #101)

Ideally this button is available to the user for no greater time than the current background calls/tasks that occur during autologin when the spinner is up so that a normal user's autologin process takes the same amount of time, there's just a cancel button with the spinner now.

**Comment by hidde** [comment]
As discussed, this would not make sense in a world where autologin is so fast that it is shown for a very short time. Let's revisit this after #106.

**Comment by hmitsch** [comment]
Short-time available buttons are a huge accessibility challenge. Let's find a better solution.

**Comment by hidde** [comment]
I've tried some PoC'ing of this today: it seems technically impossible to achieve this because of timing in most modern browsers: at the moment in time we need the Cancel-button's event to execute and its cancel-function to run, the redirect has already started running and at that point we can no longer execute the Cancelling.

With that and @hmitsch 's earlier comment in mind, I am closing this issue.
