### ISSUE TITLE
Move unminified uncacheable embedded vendor js to referenced CDN based js

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/auth0-custom-lock#105]
Currently we use [browserify](https://github.com/mozilla-iam/auth0-custom-lock/blob/2c5aa81c6a78c7ddbbfbaa43408ed42418bee8e6/gulpfile.js#L104-L110) to combine js files into the NLX HTML. This includes embedding [auth0.js](https://github.com/mozilla-iam/auth0-custom-lock/blob/2c5aa81c6a78c7ddbbfbaa43408ed42418bee8e6/package.json#L25) into the page. This results in a few things
* The vast majority of the 457KB NLX HTML page is made up of the auth0.js code
* The auth0.js code isn't minified
* The NLX page's HTTP headers prevent caching (`Cache-Control: private, no-store, no-cache, must-revalidate, post-check=0, pre-check=0`)

Can we instead reference the [auth0 CDN hosted version of the auth0.js](https://auth0.com/docs/libraries/auth0js/v9) to speed up user experience?

**Comment by hidde** [comment]
I have been pondering this myself… having it on the CDN would require a request which would cost time, having it in the page would require more KBs to be downloaded, which would also cost time. Will do some tests, the CDN might still be much faster.

**Comment by gene1wood** [comment]
I would assume the CDN would have `etags` enabled and as a result, users would use a locally cached copy for all future requests. Really the caching is the big time saving.

**Comment by hidde** [comment]
Closing this, in favour of the solution emerging in #149: move the NLX static bundles (combined CSS and combined JS) to a CDN so that we can block inline resources.

In that light, I think we can keep the Auth0 code inside the NLX bundle (so that it is one `bundle.js` that contains both Auth0 code and our own code) that can be cached and is served from one CDN that we whitelist in CSP.
