### ISSUE TITLE
Cannot login with firefox accounts using webviews

### ISSUE THREAD

**Issue by viorelaioia-zz** [mozilla-iam/auth0-custom-lock#111]
Tried this using Webview Test app in android.

STR:
1. Open Webview Test app
2. Add testrp.security.allizom.org url
3. Click Login using Firefox accounts 

Result: Error page saying that cookies and localstorage enabling is required. From what I understood from @hidde , webviews don’t expose localstorage. So firefox accounts login method won't work in apps like irccloud, slack, etc. 
![image uploaded from ios 1](https://user-images.githubusercontent.com/5293100/38373619-55994392-38fa-11e8-8339-662671c0985a.jpg)

**Comment by hidde** [comment]
Note: this applies specifically to Webviews on (some) Android devices, that lack localStorage support.

NLX has added localStorage support for Android Webviews through a polyfill. The page in the screenshot lives in the Firefox Accounts world, where localStorage is not polyfilled and therefore the login process cannot proceed in browsers without localStorage support.

**Comment by vladikoff** [comment]
> So firefox accounts login method won't work in apps like irccloud, slack, etc.


Per OAuth RFC, the login process should be done through user's system browser. In most cases WebView logins are explicitly not supported due to usability and security reasons. 

Ref: https://tools.ietf.org/html/rfc8252

@gdestuynder thoughts?

**Comment by vladikoff** [comment]
If you still want to support the WebView flow you might want to update that sample app with something like: `.setDomStorageEnabled(true);` but localstorage requirements are probably not going away any time soon (cc @rfk)

**Comment by gdestuynder** [comment]
I think we run into this problem with apps like IRC Cloud on Android (well, this one in particular, but there may be quite a few other, it's a common pattern).

My understanding from RFC8252 is that indeed, there should either be a specific handling of authentication or redirection to the systems browser. In reality though we do not control the application code, and requesting changes and specific implementation from various vendors is quite difficult if at all possible sometimes. I'd have to read up on RFC8252 a little more to see if there are other things we can do, though @rfk may know already.

All that to say, from a user UX pov having the polyfill is much better - but if we do not find a solution we'd basically have to tell users "sorry this app is not supported to login with an FxA login" - which would drive users away from FxA :(

**Comment by rfk** [comment]
> My understanding from RFC8252 is that indeed, there should
> either be a specific handling of authentication or redirection to the systems browser.

Right, specifically section 8.12 has a bunch of info on why system browser should be preferred to a webview:

  https://tools.ietf.org/html/rfc8252#section-8.12

Unfortunately, as you say, if we don't control the client application here then our options are either to polyfill enough stuff to allow it to run in a webview, or refuse to support that application.  We'll have to discuss this with FxA team to get a feel for what we're comfortable with.

I'm curious about how other OAuth security things are handled in this flow.  Is the Auth0 layer here acting as a native client with e.g. PKCE, and proxying the OAuth code dance with FxA?  Where can I read more about the end-to-end flow that's being used here?

> but localstorage requirements on FxA are probably not going away any time soon

I don't know too much about the details TBH, but it seems like we *could* add a localStorage polyfill if we wanted to without much hassle, perhaps even enabling it only for the OAuth flow rather than for all login flows.  ISTM it's more a policy question of whether we want to allow that flow to be used in a webview at all.

**Comment by rfk** [comment]
I filed an issue to investigate this a little on the FxA side: https://github.com/mozilla/fxa-content-server/issues/6114
