### ISSUE TITLE
The autologin settings in NLX does not have a button to "go back"

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/auth0-custom-lock#144]
Ex: https://auth-dev.mozilla.auth0.com/login?client=AguzdHtOAZqbB85xAnrmYzMdYXAdUJDT&action=autologin_settings

you get:

![image](https://user-images.githubusercontent.com/956866/40393878-050bfdf6-5dd6-11e8-8625-4db1d4217c69.png)

and you can't go back with a button / as a user you're a little lost, specially if you arrived here from clicking a button on the SSO Dashboard.

Proposal: add a header/top of page that looks like the SSO Dashboard to the auto login settings, so that the user can click there and get back to the SSO Dashboard

@m-branson @hidde

**Comment by m-branson** [comment]
Thanks for flagging @gdestuynder & appreciate your thoughts/efforts here @hidde.

My main concern is continuity of experience for our users. That said, I completely understand the desire to keep the code clean and provide a fix that can route our users where they need to go (as opposed to the dead end they are reaching now).

As a first iteration of this, I feel that @hidde's proof of concept above works.

As we move forward I would like to test this as a baseline vs. one or two other concepts to ensure we are achieving the most intuitive experience possible. I've captured this [here](https://docs.google.com/document/d/1sI2gHiUdb3ChZybS3m0P7DpLB51t8_8wmraUtmQc6Lc/edit#heading=h.taqjemgvurx9) and open this document to the team (esp. @hidde & @viorelaioia) to capture other concerns, ideas, assumptions that we can and should test moving forward.

This will help ensure we're putting programming efforts (like those described by @hidde above) to the right tasks & not building things the hard way based on assumption. Additionally, we can get better at road mapping feature builds further into the future. 😄

**Comment by hidde** [comment]
For until we've decided on better solutions, I have taken the liberty to go ahead with building this iteration as in the PoC above. With one minor adjustment: instead of two horizontal rules, I've removed the one between text and toggle, it now just has one between toggle and the buttons.

These changes are in what is (from my side) ready to go live as 1.4.0, it currently runs in DEV.

@viorelaioia  @m-branson Please review the updated settings screen (by choosing Enable/Disable Auto-login on sso.allizom.org). If you both think this will be a useful short-term improvement, we could ship this relatively quickly (but no pressure, we certainly don't _have_ to, it was little effort).

**Comment by m-branson** [comment]
@hidde this PoC is good by me with a small bit-pick that our ‘Back to SSO Dashboard’ button is forced to two lines of text on mobile. This leads me to wonder if we actually need to call out SSO here? ‘Back to Dashboard’ would be succinct and sufficient, yes? We made this same decision re: ‘Log out of Mozilla’ a couple months back. 

cc @kang @andrewkrug

Also note, I have not gone over this with a fine tooth comb. Trusting that @viorela will help QA as well. 😬

**Comment by gdestuynder** [comment]
I think it can be a "Go back" where going back links to the calling client_id (since its already a parameter to the request)
