### ISSUE TITLE
Add CSP to Auth0 login page and serve CSS/JS bundles from CDN

### ISSUE THREAD

**Issue by april** [mozilla-iam/auth0-custom-lock#149]
We should consider adding CSP to the auth0 login pages. CSP is supported via a `meta` tags, and so hopefully should be do-able. In my testing with Laboratory, this is basically what it produced:

```html
<meta http-equiv="Content-Security-Policy" content="
  default-src 'none';
  connect-src 'self' https://person-api.sso.mozilla.com/v1/connection/;
  font-src https://fonts.gstatic.com;
  script-src 'unsafe-inline';
  style-src 'unsafe-inline' https://fonts.googleapis.com/
">
```

We should probably also remove the inline stylesheets and scripts, of which there are a bunch. That way we can remove `'unsafe-inline'` from the policy and make it useful.

**Comment by gene1wood** [comment]
Removing the inline stylesheets and scripts would also drastically improve the page performance and user experience by being able to take advantage of caching which we currently can not. Part of that is requested in #105

**Comment by hidde** [comment]
All of the stylesheets and scripts are inline, as Auth0 lets us host one page only. The inlining has disadvantages, but it does simplify deployment and can be a performance advantage when resources are kept small as they come with the same HTTP request we need to get the HTML. If CSS/JS are kept small, they only make that request slightly larger than it has to be to contain just the login form. The plan is to fix #105 in current sprint; it takes `auth0.js` (currently ~80% of our total scripts) out of the login page, onto Auth0's CDN, and should reduce load time hugely for users that have it cached.

Having said that, removing `unsafe-inline` would change the architecture quite a bit, as we'd have to run a CDN and make a plan for releasing to that. If it is a security MUST, I'll leave that up to you both, I'll gladly do that, but otherwise I'd like to keep it at just the meta tag above if that's ok (perhaps it would be even better if Auth0 would serve the login page with that CSP policy as a header?).

**Comment by april** [comment]
We already run like 5 CDNs, so I don't think that's an intractable problem if we decide we want to fix it. Their code does do things based on the data in window.location and also sets `innerHTML`, so the potential for XSS shenanigans is there.

**Comment by gdestuynder** [comment]
note that, it would also be interesting to replace the auth0js code by our own for simplicity - which would also help make this simpler (plus way faster to load when not cached)

**Comment by hidde** [comment]
Seems like the best way to go is add CSP and serve assets via CDN at the same time.

Let's take this to Tech Alignment. The challenging bits I think are to make sure we have the right versions of the right thing on the CDN, and how to make it work in DEV.

**Comment by hidde** [comment]
As discussed in Tech Alignment, we can use `cdn.sso.mozilla.com`, for example as `cdn.sso.mozilla.com/nlx`. 

Discussed afterwards: we'd serve the full `dist` folder that comes out of the `auth0-custom-lock` node process, and serve this per branch, so that we'd have `cdn.sso.mozilla.com/nlx/MASTER/foo/bar` / `cdn.sso.mozilla.com/nlx/DEVELOPMENT/foo/bar` etc., where branch name can also be replaced by a commit hash.

**Comment by hidde** [comment]
Assigning @andrew for the CDN/CI piece.

**Comment by hidde** [comment]
There's one more thing… at the top of NLX we have some JS that gets executed before everything else, for example to do a redirect in certain circumstances. In #106 there's a request that would also require a few lines of code there. 

This is the last piece in the way of removing `'unsafe-inline'`. I think these are the choices and I don't have a strong opinion on this:

* keep `unsafe-inline` so that we can have a few lines of inline code to do superfast redirects without loading other assets (current use cases: SSO logout; future use case: faster connection lookup) 
* remove `unsafe-inline`, this will slow down logout, but increase peace of mind 

What do you think @gene1wood / @april / @gdestuynder / @andrewkrug ?

A third option could be to add a `nonce` to the inline script, but because we're not serving this ourselves, generating these would not really work with how configs work currently (and it is probably not worth the time investment to change that).

**Comment by hidde** [comment]
Having looked further into this, we _have_ to have inline script in order to take the configuration object from Auth0, because that is how it is passed. So `unsafe-inline` is necessary for NLX to function.

**Comment by gene1wood** [comment]
A bit more detail : Auth0 has a special template variable [`@@config@@`](https://auth0.com/docs/hosted-pages/login#parameters-for-the-authorize-endpoint) which they replace with a JSON  string in the hosted lock page. We then parse that JSON to get access to the data.

Now that I think about it, to work around this and still remove `unsafe-inline` could we
* Put the `@@config@@` template variable inside a non-displayed (via CSS) DOM element
* Have code in the non-inline CDN scripts which grab the text payload of that DOM element and parse it to extract the data?

This way there's no inline javascript and we can still access the JSON data.

**Comment by hidde** [comment]
I could put it in a data attribute, let me experiment with that tomorrow. 

Moving the logout code to a CDN may prove trickier (or slower than current situation) but  not impossible.

**Comment by hidde** [comment]
Update: all inline JS is now in a bundle that we can serve from a CDN.

**Comment by april** [comment]
> keep unsafe-inline so that we can have a few lines of inline code to do superfast redirects without loading other assets (current use cases: SSO logout; future use case: faster connection lookup)

I will add that this largely isn't true in an HTTP/2 world, as browsers will immediately start pipelining that file concurrently with loading the HTML.

**Comment by hidde** [comment]
This was deployed last night, we now enforce a CSP and serve all assets via the Mozilla SSO CDN.
