### ISSUE TITLE
Improve NLX in account verification mode

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/auth0-custom-lock#168]
Expected: the autologin button is turned off, and maybe even grayed out in this case

**Comment by gdestuynder** [comment]
also, shouldnt this slide left to right to enable?

**Comment by hidde** [comment]
I've removed the autologin setting for users that are account linking (cc @m-branson).

@m-branson Might it also make sense to change the wording for account linking here? We could technically do that whenever a user comes to NLX for account linking.

Maybe along these lines:

<img width="543" alt="screen shot 2018-06-12 at 14 02 51" src="https://user-images.githubusercontent.com/178782/41289251-767c459e-6e49-11e8-9448-766a4f6d8fa4.png">

?

**Comment by m-branson** [comment]
Agreed that we should remove auto-login on this screen.

That said, I see us getting into an interesting space of 'NLX settings' here (including the auto-login settings screen). The preferred method for the account linking user flow would not be to have users choose from multiple identity providers in this screen as they do now. Instead users should see the available identity providers listed on their mozillians.org profile settings page rather than being hidden behind an 'add identity' button. When clicked users will be routed through NLX to confirm _only_ that connection. 

Eg:
1. navigate to mozillians.org profile settings 
2. Show _individual_ buttons for each identity option
  a. `Add Email`
  b. `Add Firefox`
  c. `Add GitHub`
  d. `Add Google`
3. When clicked, user is routed to NLX where they are prompted to continue _only_ with that identity.
I've hacked this mockup together quickly to show copy recommendations & changes to button text (e.g. "Back to Profile Settings" rather than "Back to Dashboard"). In the case of an email the email field would be shown.
![add-identity-mock](https://user-images.githubusercontent.com/18686986/41629596-2df26326-73df-11e8-9261-c4b33a359ad1.png)

Thoughts? cc @akatsoulas @johngian @viorelaioia

**Comment by hidde** [comment]
I like the above! 

Something else we could do, maybe food for thought, is trigger a log in for the specific method without showing NLX. So instead of doing that login when user clicks the button, do it as soon as NLX loads. 

But as I said, I like the above, makes it more of an intentional choice to click the button, too (and allows for going back to settings).

**Comment by gdestuynder** [comment]
NOTE: our method of doing account verification still utilizes our authentication stack and creates users automatically in Auth0. The method we prefer, and that apparently will be used for Bugzilla verification, is to directly verify through Mozillians.org instead of requesting a login (except for LDAP, which is correctly/technically a login request)

I just want to make it clear that we ideally want to stop doing that, so the work above are still work around (though, it looks great otherwise and make its a much nicer work-around UX wise).

I'm adding this note in case this changes your priorities or anything like that.

cc @akatsoulas  as FYI

**Comment by m-branson** [comment]
Thanks @hidde & @gdestuynder, both very helpful comments.

The account verification piece is a much larger topic that I believe we should take to a different environment. Eg; tech alignment or new issue.

I am working to better determine how & where account verification should take place both technically & for our users. This is the first I've heard that it is preferred to be done through Mozillians.org & not route through NLX (had no idea this was a technical work around).

I will open a separate issue to track this conversation & have also tagged Kang's comment in our Open UX Questions sheet.

That said, it seems we have actually resolved the original need for this issue?

**Comment by hidde** [comment]
Agreed, the original issue (autologin switch goes into wrong direction) is resolved, thanks @kang for noticing! Let's continue in #58!
