### ISSUE TITLE
Password managers broken on iOS in Chrome / Firefox

### ISSUE THREAD

**Issue by april** [mozilla-iam/auth0-custom-lock#173]
More information can be found here:

https://discourse.mozilla.org/t/ios-safari-passwords-key-icon-is-not-shown-on-sso-password-field/28411/4?u=atoll

But the gist is that while password managers sort of work in Safari, they don't work at all in Chrome or Firefox.

**Comment by floatingatoll** [comment]
Steps to reproduce:

1. Install Firefox and Chrome on iOS 11.latest.
2. Navigate Safari, Firefox, Chrome to the login form at https://sso.mozilla.com/. If necessary, logout and retry.
3. Tap on the username field.

Expected result:

Above the iOS keyboard is a new bar with a keychain icon on the far right and any iOS saved passwords shown on the left. Tapping either a password entry or selecting one through the key icon autofills both the username and password fields.

Actual result:

Safari: Only the username _or_ password field is autofilled, requiring two interactions with the password manager. This falls short of awesome, but is certainly better than the other two.

Firefox, Chrome: iOS doesn't recognize either the username or password fields as an opportunity for the keychain.

Notes:

All three mobile browsers correctly show the keychain bar on third-party non-Auth0 sites with normal login forms.

Safari

**Comment by hidde** [comment]
Thanks @april for filing an issue and @floatingatoll for the additional info and steps. 

Password manager compatibility is high priority for our login form, as password managers let people have long and unique passwords. We've learned along the way that password managers can have complex heuristics for figuring out what email and password fields are, especially in multipage forms like ours, and do various things to increase discoverability (web standards, autocomplete attributes, non standard hiding).

Having said that, I've looked into our Analytics for the login page and it seems that Firefox/Chrome for iOS are around 0.6% percent of total visits (in the past three months). I assume it might be a little bit higher, because we don't track people with Do Not Track on, but I'm afraid for now I'll have to mark this issue as Low Priority.

**Comment by april** [comment]
Low priority or not, it does look kind of embarrassing when we can't make our own login page work in our own browser. That goes doubly so when our official recommendations are both to use Firefox and to use password managers.

**Comment by hidde** [comment]
> Low priority or not, it does look kind of embarrassing when we can't make our own login page work in our own browser. That goes doubly so when our official recommendations are both to use Firefox and to use password managers.

It does… 

On the bright side, login works if you copy/paste passwords from a password manager like I do. Saving passwords using iOS Firefox's built in password manager also works, by the way. So there are some options.

I'd love it to also work with the password bar @floatingatoll mentions, but these kinds of issues are hard to debug as we have no knowledge of iOS's heuristics (and have already built the form fields to be easy to recognise). With few people affected it seems sensible to give it a low priority.

**Comment by floatingatoll** [comment]
To confirm, Firefox/Chrome for iOS are around 0.6% of *total* visits, or of
*mobile* visits, to Auth0?

**Comment by st3fan** [comment]
Some quick testing on iOS 12b2:

- Safari: Works - suggests and fills both username and password correctly
- Firefox 12.1: Fails - does not suggest username or password
- Focus 4.1: Fails - does not suggest username or password

Unclear why Safari has a better experience. It _may_ be because Firefox and Focus are not linked against the new iOS 12 SDK. Can investigate later.

**Comment by april** [comment]
I've already made some progress on this, getting Chrome to allow both usernames and passwords and getting Firefox to allow usernames.

**Comment by april** [comment]
Scratch that, I think I've got them both working.  :)

**Comment by hidde** [comment]
@floatingatoll: that’s of total tracked visitors (I assume we also have visitors with DNT). 

I am very curious and look forward to your PR, @april.

**Comment by april** [comment]
Looking at LastPass's code, it seems to be pretty stubborn about not filling / detecting hidden elements. While Firefox Focus will work with old autofill if the element is specifically `hidden` and un`hidden`, it won't do it any other way. I can't seem to find any way that works with both Firefox Focus and LastPass Desktop.

After a bunch of investigation, I've found that Firefox Focus has trouble filling forms on Tumblr.com, another site with a SPA multi-screen login form. Safari does not. 

I still think we are approaching this the wrong way, so maybe LastPass will have some advice on how to handle this? The way it is done now is really suboptimal.

@st3fan, could you see if linking to iOS 12 makes this problem go away? If so, I guess the best bet could simply be to wait.

**Comment by hidde** [comment]
@april In a ~ 1 month support ticket exchange with quite a bit of back-and-forth, I've ended up asking them quite specificially: 

> Do any of these things matter:
> * use of display none or hidden attribute
> * the URL the user/password screen is on
> * name or id attributes on the fields
> * type of the field 

… they did not answer that. I've since concluded it is `display: none` (and with that the `hidden` attribute as that is set to `display: none` in user agent stylesheets).

**Comment by april** [comment]
This is what they use to detect if an entry is hidden:

```javascript
function LP_treat_as_hidden(e) {
    if (!e) return !0;
    if ("hidden" == e.type) return !0;
    if (!e.parentNode) return !0;
    if (0 == e.id.indexOf("hidden") && ("none" == e.style.display || "none" == e.parentNode.style.display)) return !0;
    if ("true" === e.getAttribute("aria-hidden")) return !0;
    var t = e.getAttribute("hidden");
    return !(!t || "false" === t)
}
```

There are many points at whether it decides to fill the form (and the code is very long and complex, as you might imagine), but I don't see any way to hint to LastPass that it is a hidden field that will be unhidden and should be autofilled.

**Comment by april** [comment]
After another few hours of debugging, the function that detects that it's a form with a password (`chk_form_has_password()`) also checks to see if the offset height/width are 0. If they are – and hidden elements always are – it returns false.

I have a couple other ideas, I'll keep poking away at it.

**Comment by april** [comment]
After mucking with `chk_form_has_password()` a bunch, I realized it just has to have one – off screen or not – to trigger the autofilling. Once the page is loaded, it can be removed.

**Comment by april** [comment]
That said, try again on the dev site and see if that works for you.  :)

**Comment by april** [comment]
Ugh, now it seems to not be working again for me. Let me keep poking at it and see what the heck is wrong now. LastPass is the worst.
