### ISSUE TITLE
Upon deploying from master branch, version live in dev changed from 1.6.0 back to 1.5.1

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/auth0-custom-lock#256]
The HTML live in dev (manually deployed there) which referenced GitHub pages instead of the CDN had a version of `1.6.0`. When I triggered codebuild auto deployment from `master` branch, it made 3 changes to the HTML
* Version changed from `1.6.0 to `1.5.1`
* Asset references changed from GitHub pages to the CDN
* references to `auth0.org` were changed to `auth0.com`

I've looked and don't see if the `1.6.0` version number came from somewhere or was just made up. `package.json` shows the version as [`1.5.1`](https://github.com/mozilla-iam/auth0-custom-lock/blob/952c9bc6f6fd15169697378da50c895a922a5fb8/package.json#L3)

Is this change of version ok or a problem?

**Comment by hidde** [comment]
@gene ah, that was me manually updating the version number in the source code on DEV, so that anyone curious could distinguish it from what's on PROD.

Before merging to `production` we should manually update the number in `package.json` (and in the CHANGELOG.md, but I see that's already up to date).

**Comment by gene1wood** [comment]
Got it, that makes sense. #258 is a PR to bump the version to match the `1.6.0` in Changelog
