### ISSUE TITLE
Auto-login should not work on the third login performed in less than 10 seconds

### ISSUE THREAD

**Issue by rleitan** [mozilla-iam/auth0-custom-lock#279]
[Steps to reproduce]:
1.Open https://aai-low-social-ldap-pwless.testrp.security.allizom.org/
2.Enable autologin, login then log out
3..Open https://aai-low-social-ldap-pwless.testrp.security.allizom.org  (in less than 10 seconds) then log out
4.Open https://aai-low-social-ldap-pwless.testrp.security.allizom.org/

[Expected result]:
Auto-login should not work on the third login performed in less than 10 seconds

[Actual result]:
Auto-login is performed

**Comment by hidde** [comment]
Hi @rleitan ! I just learned that the interval for us preventing autologin for second attempts and beyond [has been reduced to 5 seconds](https://github.com/mozilla-iam/auth0-custom-lock/pull/266/files) because of issue #249. From what I just tested it looks it behaves as expected if in your STR we change 10 to 5. 

(Context for anyone reading along: this means we will prevent autologin if it is triggered again in the same 5 seconds. This is something we added to get people out of autologin ‘loops’. We started with 10 minutes, this was reduced to 10 and then 5 seconds).

I think user experience has regressed here (cc @mbransn), for cases where NLX is triggered in side applications.

_Example: I recently found myself reinstalling Slack from scratch, because my Mozilla Slack account was autologging in with no way to stop it, because 10 (now 5) seconds is not enough to close the login window in Slack and trigger a fresh one._

I do think 5 seconds is better than nothing, because it does still let users stop autologin by refreshing when they see the message “Attempting to autologin”. Pressing refresh _is_ doable in 5 seconds.

I propose we close this issue as I see no way we can make this better, without undoing the solution that solved #249.
