### ISSUE TITLE
Speed up automatic login

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/auth0-custom-lock#32]
Since we now lookup connection information before doing an automatic login, this slows down the auto-login process.

Here are some ideas to restore it's former glory/speed, by order of "meh" to "best" solution, that I could think of so far

A) Cache connection information in localStorage every time we see a new RP client-side with some expiry (for ex, 3 days), use cache whenever possible before the connection is made

B) enforce RP to support certain login methods, for example, always support LDAP (and thus call auto-login before anything else for LDAP), or LDAP+GitHub (same logic)

C) check the re-login logic with unsupported connection methods, so that auto-login gets attempted, then fail, then the login page is loaded again and waits for an actual interactive login

**Comment by hidde** [comment]
This is a relatively old issue, some of the things here have already improved. 

In addition, we will be improving speed in next release, because [we will serve assets from our CDN](https://github.com/mozilla-iam/auth0-custom-lock/issues/149) and most users will be able to use their cached version of our scripts. Answers below are with our new external-scripts-only approach in mind.

> A) Cache connection information in localStorage every time we see a new RP client-side with some expiry (for ex, 3 days), use cache whenever possible before the connection is made

I like the idea, but with what we've learned over the past months, I'm hesitant to do this, because at no point does NLX know whether someone actually authenticated (or went back because made wrong choice). We might be putting connection info for potentially unwanted connections into people's `localStorage`.

> B) enforce RP to support certain login methods, for example, always support LDAP (and thus call auto-login before anything else for LDAP), or LDAP+GitHub (same logic)

I think this almost already works, if you've logged in with LDAP to an RP, that will be your autologin method (and with our switch the behaviour can be turned off). 

> C) check the re-login logic with unsupported connection methods, so that auto-login gets attempted, then fail, then the login page is loaded again and waits for an actual interactive login

I think in our CDN reality this can't really be faster, most of the time will be in downloading the JS file. Showing the spinner while waiting at least lets us show the user what's happening.

So currently I think we cannot make this faster, as the lookup and autologin timing will be relatively close and we have other speed improvement . Closing this issue (feel free to reopen).
