### ISSUE TITLE
Clicking "Log in to Mozilla SSO" from sso logout page automatically logs me in with github, if I was previously logged in with github

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/auth0-custom-lock#33]
**STR:**
1. Login with github to sso.mozilla.com
2. Click Logout button 
3. On Sign Out page, click "Log in to Mozilla SSO" button

**Expected:**
The lock is shown.

**Actual:**
The lock automatically logs me in with the github account that I previously used. 

Note: This is not happening if I previously logged in with LDAP.

**Comment by hidde** [comment]
Do you see NLX  before logging in with GitHub or does it not even go to NLX?

**Comment by viorelaioia** [comment]
I see NLX and "Autologging in with github" message before logging in with github 
![login after logout](https://user-images.githubusercontent.com/5293100/37908714-a8e1ddb6-3111-11e8-8aef-7d37b1a6fd1a.png)

**Comment by LeoMcA** [comment]
I've just (accidentally) repro'd this.

This is quite a nasty bug as there's no way to get out of the loop without deleting auth0's localstorage data, which I only found out after @viorelaioia told me. The usual "login screwed, let's nuke my cookies" mindset didn't work.

**Comment by andrewkrug** [comment]
Just to ensure that our language is correct per component here I'll further clarify this.

When a user hits the federated logout URL https://sso.mozilla.com/logout the auth0 session is destroyed but you do still have a session with github.  The _smart lock_ remembers your connection preference the next time you are redirected to the signin page and logs you back into auth0 using the valid github session creating a brand new auth0 session.

The sso dashboard has no way to clear the local-storage for the NLX preference due to security restrictions on who can interact with local storage.  I'm open to suggestions though on how we'd like to handle things ( not be a local storage expert )

**Comment by gene1wood** [comment]
This was reported in #17

**Comment by viorelaioia** [comment]
This is fixed in staging, as now sso dashboard logout clears last used login from localstorage. So fresh nlx is shown when trying to login again (after sso logout)
