### ISSUE TITLE
Allow user to see autologin method and cancel it

### ISSUE THREAD

**Issue by hidde** [mozilla-iam/auth0-custom-lock#34]
So this is an idea I've had which could solve various use cases:

* users that use different login methods for different RPs; we often do not know what they intend to use when
* users that are being auto logged in, but they wanted to change their login method
* sometimes users benefit from being autologged in, but sometimes it gets in the way from what they want to do (i.e. when autologging in to an RP they don't want to or can't use). It's hard to predict which of the two it is in a given situation.

## The idea

When loading NLX, if cache has a connection stored, we check if that is a connection we can autologin with. During the check, we show a spinner, and two more things:

* text ‘Automatically logging in with [login method]’, i.e. ‘Automatically logging in with GitHub’
* button that allows to cancel autologin; it will prevent a redirect from happening and just show NLX

To make this work, we will need to show this screen for slightly longer, so that users have a chance to respond. 

## How it is different 

This makes it slower rather than [faster](https://github.com/mozilla-iam/auth0-custom-lock/issues/32), but I am expecting that giving users insight in what's happening will make it _feel_ less like waiting (it improves ‘perceived performance’).

I think this may offer ‘best of both worlds’.

**Comment by m-branson** [comment]
@hidde this is inline with what we talked through and I'm still aligned from a UX perspective. Agree that intentionally improving perceived performance is most important. The main barrier we want to avoid is requiring our users to click for auto-login (e.g. old lock).

This new flow ensures auto-login is indeed automatic; provides users with feedback as to which account they are auto-logging in with; and allows users to cancel or change this account during the auto-login process.

**Comment by gdestuynder** [comment]
I would not do this. In reality, it's just annoying users.

The vast majority of users do not change login methods, and when they do, we do NOT control what user is logged in. Auth0 is NOT called every time you load a page thus give the wrong expectation.
The only thing that works to change identity is container tabs and equivalent mechanisms.
I'd rather we indicate that you should log out on the SSO dashboard instead.

**Comment by gene1wood** [comment]
I think we should instead communicate to users a way for them to indicate that upon their next login (or next login to RP foo) they want to be able to choose their identity. This way we don't slow down the flow but we still have an obvious way for users to, before going to discourse for example, indicate that when they get there, they want an opportunity to choose their identity.

From a technical standpoint, I don't know how we do this, is it just logging out of Auth0?

**Comment by gdestuynder** [comment]
> From a technical standpoint, I don't know how we do this, is it just logging out of Auth0?
either log out of auth0 or set the parameter that disables auto-login. this can be done in the dashboard for ex as the parameter is per login/per connection (i.e. you can decide where/when it's set)

**Comment by m-branson** [comment]
It sounds as though we need to teach our users (over time) to manage their login preferences within the SSO Dashboard. UX preference is to forgo over-engineering an account management solution within NLX and keep the login experience as smooth/quick as possible.

As a front-end compromise I propose we provide users with visual feedback during the login transition that appears to still be the NLX, even if it technically isn't (e.g. the spinner on an NLX card). This provides grounding as a user transitions from NLX to an RP, rather than hanging in a visual void. _I believe we all agree with this?_

What are our technical requirements to provide an accurate UX around RP login preference within the dashboard? And how do we start to enroll users in using the dashboard more readily? _Thinking this may be a good time for the IAM project to start more clearly promoting the link between the SSO Dashboard and NLX to the greater user base. What seems obvious to us is generally not the case to a wider audience._

cc @hmitsch @andrewkrug

**Comment by gdestuynder** [comment]
we should probably merge this with #43 and/or close one

**Comment by jryans** [comment]
As a user with two identities (personal vs. staff), I was perfectly happy with the extra step we had before as it allowed me to confirm which should be used. I hope that some solution can be found here so that containers aren't required for this case.

While I understand containers have benefits on their own, I don’t like being forced to use container tabs to separate identities when it worked perfectly well before the auto-login changes.

**Comment by m-branson** [comment]
@jryans thanks for the input, very much appreciated. We're actively looking into how best we move forward here and will be exploring various options to best balance desires for speed vs. desires for account management.

@gdestuynder agreed re: merging issues. Propose we close this and focus conversation on #43 as it is closer to a user story than a solution?

**Comment by hidde** [comment]
The ‘Show login method’ part of this issue has been solved and is currently in NLX.

As per Megan's comment above and our IAM Tech Alignment discussion on 7 March, we will look at user stories before jumping to solutions and for now not implement a Cancel button. Closing this issue for that reason.
