### ISSUE TITLE
NLX stay in waiting state if a login method fails

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/auth0-custom-lock#44]
Ex:
- login to an RP without LDAP enabled in Auth0, enter username, password, click login
- NLX shows a spinner while the login is being performed
- auth0js (NLX uses that lib) POSTs login attempt to it's own endpoint, which returns 404
- NLX  still shows a spinner instead of an error

In order words, NLX or auth0js does not process return codes that are errneous (at least not 404)

Note: In practice this is a rare issue, since right now (and since today really) all RPs have LDAP enabled. However, since we cannot always guarantee login methods work (eg "github down" "LDAP is down" etc.) informing the user that something has failed would be bette

**Comment by hidde** [comment]
@gdestuynder Do we have an PR that doesn't have LDAP we could test this on? Saw one on Test RP but it uses `PROD` NLX.

**Comment by hidde** [comment]
We're displaying some errors that Auth0 returns, but in the case of a non-existing login method, Auth0 simply returns plain text (`connection not found`), not an error object.

Since we're already checking RP supported login methods, I've added a custom error page to NLX that is shown if a user has gone to a  RP doesn't support LDAP login.

Other unsupported RPs are simply hidden, in  the case of LDAP hiding isn't really helpful: the email field is also used for passwordless, and the second screen only shows after we see an LDAP screen.

Like you said, in practice this is (almost) impossible to happen as all PRs have LDAP enabled.
