### ISSUE TITLE
Trying to login to sso dashboard after logout shows first the autologin message, then nlx  

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/auth0-custom-lock#62]
STR:
1. Login with LDAP to sso dashboard 
2. Logout
3. Click "Log In to Mozilla SSO" butoon

Expected:
NLX login window is shown

Actual:
First the spinner and "Autologging in with Mozilla-LDAP" message is shown, then the NLX login prompt

**Comment by gdestuynder** [comment]
can anyone reproduce this? @hidde @andrewkrug

**Comment by gdestuynder** [comment]
I suspect its the same as #59 and #58 (I'm almost sure its the same but not 100%)

**Comment by hidde** [comment]
I can reproduce. What's happening is that sometimes when we're performing an autologin, Auth0 does not let the user log in and returns them a new login form. Verified that the login method is correctly sent to the endpoint, not sure about `state`, `nonce` and or cookies.

**Comment by hidde** [comment]
This happens because we have no way of knowing whether an autologin is going to work. Auth0 decides if someone gets logged in after applying all the rules, i.e. we cannot know what the result is until after they've applied the rules.

So we try, and then either: 

* it works
* user is sent back to NLX

(the latter is what is happening in this bug)

@kang and I discussed one way to get around it, by performing a fake login, then if that worked perform an autologin. But this would slow things down. Having autologin 'fail' and falling back to NLX is a preferable UX imho.

Cannot fix 😢  

(cc @m-branson @viorelaioia )

**Comment by hidde** [comment]
After discussion with @m-branson, actually we can do something about this. 

Changing the wording to “Attempting auto-login with [method]” on NLX and labelling this issue as “Ready for test”.

Thanks @m-branson!
