### ISSUE TITLE
Clarify which password is being asked

### ISSUE THREAD

**Issue by nukeador** [mozilla-iam/auth0-custom-lock#80]
Volunteers con community LDAP accounts will find the auth0 confusing since it's asking them for a password when they use their email (instead of passwordless option).

I think the workflow should clarify that the password being asked is the Mozilla LDAP one, something clear for mozilla staff email but not for some volunteers emails.

Cheers.

**Comment by hidde** [comment]
cc @m-branson

**Comment by m-branson** [comment]
@hidde @gene1wood my understanding is that LDAP users who have a password will always be prompted for their password, as it is the most secure option. Therefore they should not be routing to the passwordless/third-party screen at all. Is my assumption correct? 

Alternatively, users who have never utilized a password login (or are not LDAP) will be prompted with the passwordless/third-party option screen after entering their email.

@nukeador do you have community members reporting this confusion or is this something you are flagging as a potential issue? The ultimate UX goal of the new login experience is that it is 'smart' and provides users with the appropriate option (password or passwordless) based on the email they enter. Therefore users who have never previously entered a password will not be prompted to enter a password now. If you have contributors who are experiencing this differently it'd be great to log those issues separately.

**Comment by gene1wood** [comment]
@m-branson If a user enters an email address that has an associated LDAP account, they'll be presented with the password field.

I think what @nukeador is talking about is for example

1. Community member goes to a Mozilla site and types in john.doe@yahoo.com
2. NLX determines that they have an LDAP account and takes the user to the second page with the password prompt
3. User looks at the second page and sees the word "Welcome", a text box with the word "password" in it and an "Enter" button and ponders which password to type. Maybe they've forgotten that they have an LDAP account. Maybe they wonder if they should type their yahoo password.

I've often felt this same confusion when I get to the password page. I'm not entirely sure the source of the feeling but I've noticed it.

For comparison, Google's second page where you type in the password says "Welcome" and the email address of the account you're trying to log in as below it, cueing the user about what password they're looking for (the password associated with the email address).

This might make it more clear.

@nukeador are there users who either
* on some sites see a passwordless login (because the site doesn't support LDAP) and on other sites see an LDAP password login (because the user is an LDAP user)
or
* used to get a passwordless login on a site and now get an LDAP password login

**Comment by m-branson** [comment]
Thanks @gene1wood -- I'm interested to hear @nukeador's response to your question after the clarifying statement.

**Comment by nukeador** [comment]
"used to get a passwordless login on a site and now get an LDAP password login"

It personally happened to me with my personal community email, which was asked for a password but I didn't know which password to type (I didn't remember this was a community LDAP email).

**Comment by hidde** [comment]
This is being addressed in #108, we now explicitly say “LDAP password” with the password screen. Where it currently says “Welcome”, it will say “Please enter your LDAP password”.
